### ISSUE TITLE
The Plan

### ISSUE THREAD

**Issue by jdantonio** [AkronCodeClub/sicp-study-group#3]
A group of us met tonight at Panera and planned out a study group for SICP. I'll be posting more information to the Akron Code Club meetup page and to this repo. Everyone is welcome to join, even if you were not able to meet with us tonight.
## In a Nutshell

Out study group will follow the [MIT SICP](http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-001-structure-and-interpretation-of-computer-programs-spring-2005/) course. We will complete the first 8 lessons and the first programming project. We will meet in-person twice a month to conduct code reviews and share answers. Upon completion we will conduct a retrospective and decide if we want to form another study group to continue on.
### Curriculum
- [2005 SICP course at MIT](http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-001-structure-and-interpretation-of-computer-programs-spring-2005/) hosted on MIT OpenCourseWare.
- We will follow the structure of the [course calendar](http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-001-structure-and-interpretation-of-computer-programs-spring-2005/calendar/) completing L1-8 and R1-8.
- This corresponds to [readings](http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-001-structure-and-interpretation-of-computer-programs-spring-2005/readings/) L1-8.
- This corresponds to [video lectures](http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-001-structure-and-interpretation-of-computer-programs-spring-2005/video-lectures/) 1A, 1B, and 2A.
- We will work on one lesson and one reading per week, and do all of the assignments (exercises and problem sets) in order, with one exception. We will work on Project 1 at the same time as R8 and L8.
### Meetings
- We will meet twice a month on the first and third Mondays (the monthly Code Club meeting is on the second Monday).
- Meetings will correspond with _even numbered_ lessons (2, 4, 6, 8).
- We will have an optional InstallFest meeting prior to the first official meeting.
- We will have a optional retrospective meeting after the final official meeting.
- If we decide to continue with the course we will use the retrospective to plan the next phase.
- A different member of the study group will volunteer to facilitate each meeting.
- Each meeting will last no more that two hours.
- The location of the meetings is to be determined but will be in Fairlawn (probably the Panera where we met today).

Study group members are encouraged to organize in-person and virtual meetings throughout the course. Feel free to use the [Akron Code Club](http://www.meetup.com/AkronCodeClub/) meetup page and GitHub [issues](https://github.com/AkronCodeClub/sicp-study-group/issues) to organize meetings. [Google+ Hangouts](http://www.google.com/+/learnmore/hangouts/), [Gitter](https://gitter.im/AkronCodeClub/sicp-study-group), and other free tools are available for those who cannot meet in person.
### Tools
- The primary scheduling tool will be the [Akron Code Club](http://www.meetup.com/AkronCodeClub/) meetup page. Every meeting will be entered into meetup.
- We will share code through this GitHub repo. Every study group member will be given commit access and a subdirectory of their own.
- Online discussions will use the [issues](https://github.com/AkronCodeClub/sicp-study-group/issues) page of this repo (_not_ the discussion forums in meetup).
- Online chatting will use the [Gitter chat room](https://gitter.im/AkronCodeClub/sicp-study-group) for this repo.
- Study group members are encouraged to use [pull requests](https://github.com/AkronCodeClub/sicp-study-group/pulls) and commit comments to perform code reviews.
- All assignments will be done using the [MIT Scheme](http://www.gnu.org/software/mit-scheme/) programming language.
- Study group members are encouraged to complete assignments in other languages if they are interested and time permits, but this will be solely for fun and additional learning.
### Assignments
- Assignments (exercises, problem sets, and project) will be post as [milestones](https://github.com/AkronCodeClub/sicp-study-group/milestones) in this GitHub repository.
- Each week we will choose ~3 "required" exercises. These are the exercises that we will review at the regular meetings and should be considered the minimum commitment.
- Projects [0 and 1](http://ocw.mit.edu/courses/electrical-engineering-and-computer-science/6-001-structure-and-interpretation-of-computer-programs-spring-2005/projects/) are due in weeks 2 and 8, respectively.
### Expectations

The study group is a collective endeavor. To be successful as a group we ask that all participants adhere to a few agreed upon responsibilities. We agree that the success of this group depends on us working together in a supportive and respectful manner. Thus we ask all participants to meet the following expectations:
- RSVP to all meetings using the RSVP feature of [Meetup.com](http://www.meetup.com/AkronCodeClub/).
- Honor your RSVP. If you RSVP for a meeting and later decide you cannot attend change your RSVP to No.
- Read the required readings before each meetup.
- Do at least the "required" exercises before each meetup.
- Submit your code to GitHub before each meetup.
- Be prepared to discuss your solutions to the "required" problems during each meetup.
- Time permitting, endeavor to answer questions about and discuss your code online in GitHub. 
- Provide respectful, helpful code reviews during the meetups.
- Time permitting, provide respectful, helpful code reviews online through GitHub.
- Attend as many of the regularly scheduled meetings as possible.
#### Code Review Guidelines
- [CodeProject](http://www.codeproject.com/Articles/524235/Codeplusreviewplusguidelines)
- [MSDN](http://msdn.microsoft.com/en-us/library/ms182019%28v=vs.100%29.aspx)
- [thoughtbot](https://github.com/thoughtbot/guides/tree/master/code-review)
## Assignment and Meetup Timelines

Can be found [here](https://github.com/AkronCodeClub/sicp-study-group/issues/16)
### To-do
- [x] Post your GitHub username to this issue or the [planning issue](https://github.com/AkronCodeClub/sicp-study-group/issues/1) #1 so you can be given access to the repository **(ALL)**
- [x] Add all meetings to [Meetup.com](http://www.meetup.com/AkronCodeClub/) (Jerry)
- [x] Post all assignments as [milestones](https://github.com/AkronCodeClub/sicp-study-group/milestones) in GitHub (Jerry)
- [x] Verify Panera as the meeting location or find an alternate (Jerry)

**Comment by grantwinney** [comment]
Jerry, I posted under issue #1 but it's closed, and I don't know if it notifies you of new responses when an issue is closed. My github username is @grantwinney.

**Comment by jdantonio** [comment]
@grantwinney Sorry for the delay. I did receive a notification from the closed thread, but I was at home sick. I've added you now.

**Comment by jonknapp** [comment]
@jdantonio were we all going to have commit access to this repo? or should we use forks?

**Comment by jdantonio** [comment]
Commit directly to this repo. I've sent you an invitation.

**Comment by jonknapp** [comment]
I get:

```
remote: Permission to AkronCodeClub/sicp-study-group.git denied to jonknapp.
fatal: unable to access 'https://github.com/AkronCodeClub/sicp-study-group.git/': The requested URL returned error: 403
```

Did you add `coffeeandcode` instead of `jonknapp` ?

**Comment by jdantonio** [comment]
I added @jonknapp but GitHub says you never accepted the invitation. Did you get an invitation email?

**Comment by jonknapp** [comment]
I guess not.... :(

I'll poke around for it.

Jonathan Knapp
Coffee and Code, LLC
www.coffeeandcode.com
330.510.5997

**Comment by jonknapp** [comment]
@jdantonio: found it.  sorry to waste your time.

**Comment by jdantonio** [comment]
@jonknapp You, sir, are *never* a waste of my time! :-)

**Comment by joel-bentley** [comment]
@joel-bentley

**Comment by jdantonio** [comment]
@joel-bentley Invitation sent, and I've added your directory to the repo.

**Comment by tezyn** [comment]
@tezyn joshua_r

**Comment by jdantonio** [comment]
@tezyn I've created your subfolder and give you permissions to the repo. You should receive an email from GitHub soon.

**Comment by thoolihan** [comment]
Sorry to say I am going to drop out of this. With the January and February travel schedule I have for the new job, I've already missed too many meetings and the next couple don't work either. Enjoy everyone, sorry to be missing out.

**Comment by jdantonio** [comment]
@thoolihan I'm sorry to hear that you won't be joining us, but I'm happy you've found such a great opportunity with the new gig.

**Comment by thoolihan** [comment]
Thanks @jdantonio. Once things settle down, I'll try to make one of the breakfasts or other meetings. It would be good to catch up

**Comment by jonknapp** [comment]
I might be dropping out as well.  I picked up an interesting project with a tight deadline and I haven't looked at the book much in the past few weeks.  I might catch up and stop out again, but for now it looks like it's been moved lower in my priority list.

**Comment by gvoudzon** [comment]
This is Ed Macall.   Can I beam down?

**Comment by gvoudzon** [comment]
Yeah,  I know.   "Where was I last month?"

**Comment by jdantonio** [comment]
Given the number of people who've had to drop out and that fact that I am still very far behind, I must drop out, too. If someone else wants to take over I'll happily add that person as the event organizer. Otherwise I'll just cancel.

I sincerely apologize to the few in the group that were able to keep up and were enjoying the study group.

**Comment by gvoudzon** [comment]
Are people still going to Panera Bread or the Coffee house tonight?

**Comment by rickbacci** [comment]
I'm not going now. Think we would be at 4 people, plus I'm leaving for
Denver in a few weeks anyway.

**Comment by rpottsoh** [comment]
I'm out for this evening as well.

Sent from my android device.

**Comment by gvoudzon** [comment]
I hope if some people catch up that we might still be able to pick it up again in the future.
